services:
  - type: web
    name: qcflask
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn api.app:app
    envVars:
      - key: GEMINI_API_KEY
        sync: false